version: "3.9"

services: 
  my-api:
    build: .
    ports: 
    - "8040:80"
    volumes:
      - ./app:/app/app
    environment:
    - MAX_WORKERS=10
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_REGION=${AWS_REGION}
    networks:
      - my-network

networks:
  my-network:
