FROM python:3.11

WORKDIR /app/

COPY requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY ./start.sh /start.sh
RUN chmod +x /start.sh

COPY ./start-reload.sh /start-reload.sh
RUN chmod +x /start-reload.sh

COPY ./app /app/app
COPY ./gunicorn_conf.py /app

ENV PYTHONPATH=/app

EXPOSE 80

CMD ["/start.sh"]
